### ISSUE TITLE
Support MixtureModels

### ISSUE THREAD

**Issue by bencottier** [invenia/KeyedDistributions.jl#5]
[`Distributions.MixtureModel`](https://juliastats.org/Distributions.jl/latest/mixture/#Type-Hierarchy) takes a collection of `Distribution` components. To support this with `KeyedDistribution` components, we need to overload the `MixtureModel` constructors to check that the `keys` of each component are the same.

Alternatively, we could implement `KeyedMixtureModel` that assigns the `keys` to its own field, but I'm not sure if that's useful.

**Comment by aisopous** [comment]
Related: `logpdf` of `MixtureModel` runs into problems:

E.g. the following errors
```julia
k = ["a", "b", "c"]
d = KeyedDistribution(MvNormal(m, W), k)
kmd = KeyedDistribution(MixtureModel([d, d], [0.5, 0.5]), k)
KeyedDistributions.KeyedMixtureModel([d, d], [0.5, 0.5])
@test Distributions.logpdf(kmdd, zeros(3)) == Distributions.logpdf(d, zeros(3))
```
when `KeyedDistributions` tries to reconstruct the distribution https://github.com/invenia/KeyedDistributions.jl/blob/main/src/KeyedDistributions.jl#L159

**Comment by mjp98** [comment]
Closing as #40 has been merged.
